-- require('onedark').setup  {
--     -- main options --
--     style = 'warmer', -- default theme style. choose between 'dark', 'darker', 'cool', 'deep', 'warm', 'warmer' and 'light'
--     transparent = true,  -- show/hide background
--     term_colors = true, -- change terminal color as per the selected theme style
--     ending_tildes = false, -- show the end-of-buffer tildes. by default they are hidden
--     cmp_itemkind_reverse = false, -- reverse item kind highlights in cmp menu
--     -- toggle theme style ---
--     toggle_style_key = nil, -- keybind to toggle theme style. leave it nil to disable it, or set it to a string, for example "<leader>ts"
--     toggle_style_list = {'dark', 'darker', 'cool', 'deep', 'warm', 'warmer', 'light'}, -- list of styles to toggle between
--     code_style = {
--         comments = 'italic',
--         keywords = 'none',
--         functions = 'none',
--         strings = 'none',
--         variables = 'none'
--     },
--     -- lualine options --
--     lualine = {
--         transparent = false, -- lualine center bar transparency
--     },
--     bufferline = {
--         transparent = false
--     },
--     -- custom highlights --
--     colors = {}, -- override default colors
--     highlights = {}, -- override highlight groups
--     -- plugins config --
--     diagnostics = {
--         darker = true, -- darker colors for diagnostic
--         undercurl = true,   -- use undercurl instead of underline for diagnostics
--         background = true,    -- use background color for virtual text
--     },
-- }
-- require('onedark').load()


