require("telescope").load_extension("noice")
require("telescope").load_extension("undo")
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.current_buffer_fuzzy_find, {})
vim.keymap.set('n', '<leader>fp', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.api.nvim_set_keymap('n', '<leader>fn', '<cmd>Telescope noice<CR>', {})
vim.keymap.set("n", "<leader>fu", "<cmd>Telescope undo<cr>")
